"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider, { ThemeContext } from "@/providers/ThemeProvider";
import { useContext, useEffect } from "react";
import Head from "next/head"; // Import the Head component
import { title } from "process";
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { theme } = useContext(ThemeContext);

  useEffect(() => {
    document.body.style.backgroundColor = theme === "dark" ? "#000000" : "";
  }, [theme]);
  return (
    <html lang="en">
      <Head>
        <title>Rafi Ferdos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        <ThemeProvider>
          <Navbar />
          {children}
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
