'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import ThemeProvider, { ThemeContext } from '@/providers/ThemeProvider';
import { use, useContext, useEffect } from 'react';
import { usePathname } from 'next/navigation';
import Head from 'next/head'; // Import the Head component

const inter = Inter({ subsets: ['latin'] });


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {theme} = useContext(ThemeContext);
  const pathname = usePathname();

  useEffect(() => {
    document.body.style.backgroundColor = theme === "dark" ? "#000000" : "";
  },[theme])
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head>
          <title>
            {pathname === '/' ? 'Home Page' : `${pathname.slice(1)} Page`} | Rafi Ferdos
          </title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

